### ISSUE TITLE
STDOUT logs are not forwarded

### ISSUE THREAD

**Issue by getputpost** [newrelic/newrelic-azure-functions#59]
## Description
We have multiple docker containers with application logs. We can see the application logs in our Log Analytics Workspace. They appear in a table titled: ContainerAppConsoleLogs_CL. We have a diagnostic setting to forward everything to our event hubs namespace. 

I am logging the log lines of the event hub forwarder function to the console and I never see these logs appear. I only see logs related to azure events: Retrieve Subscription and Retrieve Namespace. I see another log with metric: Incoming Request. 

In our new relic logs, we filter on the "forwarderName" attribute and choose "EventHubForwarder". The stdout application logs are not making it to new relic. It doesn't appear that they are being consumed by the EventHubFowarder function either. 

Is this a setup error or is this a limitation of the current azure function?

**Comment by jsubirat** [comment]
Hi @getputpost ! Thanks for reaching out.

Note the following regarding Diagnostic Settings: `Diagnostic settings are used to configure streaming export of platform logs and metrics for a resource to the destination of your choice.`. So, it's normal to only see the Azure-related (aka "platform") logs reaching your EventHub. In order to send your _resource_ logs to an EventHub, you should follow this documentation instead: https://docs.microsoft.com/en-us/azure/azure-monitor/logs/logs-data-export?tabs=portal

Once you're sure your logs are reaching the EventHub (I suggest to verify this by inspecting the message graphs present in EventHub), then I strongly suggest you to use our ARM template to setup the log forwarding to New Relic, as it will take care of deploying and configuring everything correctly for you, you'll just have to specify the (already existing) EventHub namespace and the (already existing) EventHub you want to forward.

You can deploy the template by following [this link](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fnewrelic%2Fnewrelic-azure-functions%2Fmaster%2FarmTemplates%2Fazuredeploy-eventhubforwarder.json). Just ensure that apart from the `New Relic License Key`, you also introduce the `Event Hub Namespace Name` and `Event Hub Name` parameters.

**Comment by jsubirat** [comment]
Closing, assuming explanation was sufficient. If there's anything else, please feel free to reopen it or create a new issue. Thanks!
